ALTER TABLE "electricitydata" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.electricitydata_id_seq);--> statement-breakpoint
ALTER TABLE "electricitydata" ALTER COLUMN "date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "electricitydata" ALTER COLUMN "starttime" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "electricitydata" ADD CONSTRAINT "electricitydata_starttime_unique" UNIQUE("starttime");--> statement-breakpoint
SELECT SETVAL('electricitydata_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM electricitydata), false);
